### ISSUE TITLE
Potential memory leak if using fmem-tmpfile.c

### ISSUE THREAD

**Issue by jamievlin** [Kreijstal/fmem#6]
I can see a potential memory leak, when using fmem_mem with tmpfile. I assume that 

What happens is when
```
void* ptr = nullptr;
fmem_mem(&fmInstance, &ptr, &size_val);

free(ptr); // required for tmpfile, but causes error for winapi-tmpfile
```

I can see two solutions to this:
1. In `fmem-tmpfile.c`, I don't see `cv.impl->buf` being assigned at all. If we assign `cv.impl->buf` to the newly malloc-ed memory, the destructor function can take care of this allocation
2. Provide an explicit USING_TMPFILE macro or some way to detect if we are using tmpfile or not. This way, we can manually free the memory conditionally when using tmpfile.

Additionally, I also see another segfault point - in line 46, `free(cv.impl->buf);` is called without prior checking if buf is NULL or not. This can cause segmentation fault

**Comment by Kreijstal** [comment]
Hi, thank you! do you want to write a pull request for it?

---
Since I wouldn't like to see implementation leaking, option 1 seems the better one.

**Comment by jamievlin** [comment]
Sure, I can write a PR for this

**Comment by jamievlin** [comment]
@Kreijstal PR is now up
